CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS pois (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    estimated_cost NUMERIC(10, 2) NOT NULL,
    rating NUMERIC(2, 1),
    sentiment_score NUMERIC(3, 2) DEFAULT 0.80,
    location GEOGRAPHY(POINT, 4326) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS pois_location_idx ON pois USING GIST (location);